### ISSUE TITLE
Audioplayer does not show buffer status

### ISSUE THREAD

**Issue by pimjansen** [fearfm/website#37]
The audio player should show a buffer status when its buffering. My suggestion would be to show a spinning thing where we hold the play/pause button as well.

**Comment by vanderSangen88** [comment]
Needs to be tested if it's working as it should be. 

Based on current docs/issues in https://github.com/CookPete/react-player, no option is available yet to get the progress of the buffering. Would have been nice to show as value inside the MUI CircularProgress-component.

**Comment by pimjansen** [comment]
I suggest we close this for now since atleast we show an indication that the buffering is busy though. We can always improve at the end
